In [1]:
# Importing Packages
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense
from sklearn import datasets

In [2]:
# Loading Dataset
data = datasets.load_iris()
print(data)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [3]:
x = data.data
y = data.target
z = data.target_names
print(data.feature_names)
print(x[0])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
[5.1 3.5 1.4 0.2]


In [4]:
# Split Dataset
from sklearn.model_selection import train_test_split
x_train, x_test,  y_train, y_test = train_test_split(x, y, test_size=0.3)

In [5]:
# Data Shape
print(x_train.shape)
print(x_test.shape)

(105, 4)
(45, 4)


In [6]:
# Building the Model
model= Sequential()
model.add(Dense(100,input_shape=(4,), activation="relu"))
model.add(Dense(3, activation='softmax'))

In [7]:
# Compile the Model
model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])

In [8]:
# Fit the Model
model.fit(x_train,y_train, epochs=20)

Epoch 1/20
4/4 [==============================] - 0s 0s/step - loss: 1.0430 - accuracy: 0.3905
Epoch 2/20
4/4 [==============================] - 0s 0s/step - loss: 0.9605 - accuracy: 0.4476
Epoch 3/20
4/4 [==============================] - 0s 4ms/step - loss: 0.9215 - accuracy: 0.5810
Epoch 4/20
4/4 [==============================] - 0s 0s/step - loss: 0.8889 - accuracy: 0.6667
Epoch 5/20
4/4 [==============================] - 0s 4ms/step - loss: 0.8511 - accuracy: 0.6667
Epoch 6/20
4/4 [==============================] - 0s 0s/step - loss: 0.8180 - accuracy: 0.6762
Epoch 7/20
4/4 [==============================] - 0s 0s/step - loss: 0.7941 - accuracy: 0.6286
Epoch 8/20
4/4 [==============================] - 0s 4ms/step - loss: 0.7700 - accuracy: 0.6667
Epoch 9/20
4/4 [==============================] - 0s 0s/step - loss: 0.7440 - accuracy: 0.6286
Epoch 10/20
4/4 [==============================] - 0s 0s/step - loss: 0.7166 - accuracy: 0.7048
Epoch 11/20
4/4 [=============================

In [9]:
# Evaluate the Model
model.evaluate(x_test, y_test)

2/2 [==============================] - 0s 0s/step - loss: 0.5328 - accuracy: 0.8222


[0.5328080654144287, 0.8222222328186035]

In [10]:
# Predict for the first 10 Observations
pred=model.predict(x_test[:10])
print(pred)

[[0.7121059  0.16596898 0.12192509]
 [0.7850584  0.12485929 0.0900823 ]
 [0.03631205 0.39967054 0.5640175 ]
 [0.7176585  0.1620574  0.12028401]
 [0.8047594  0.1143699  0.08087073]
 [0.808118   0.11237073 0.07951126]
 [0.04787102 0.3886232  0.56350577]
 [0.09167576 0.43733835 0.47098592]
 [0.11797929 0.43742442 0.4445963 ]
 [0.02793446 0.3679723  0.6040932 ]]


In [11]:
p=np.argmax(pred, axis=1)
print(p)
print(y_test[:10])

[0 0 2 0 0 0 2 2 2 2]
[0 0 2 0 0 0 2 1 1 2]


In [12]:
# Prediction Result
for i in p:
  print("Predicted-Class: {},   Name: {}".format(i,z[i]))

Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 0,   Name: setosa
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
Predicted-Class: 2,   Name: virginica
